version: '3'

services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./loki-data:/tmp/loki  # /tmp/loki에 대한 호스트 볼륨 마운트
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - plg-networks

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - plg-networks

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - plg-networks

volumes:
  grafana-storage:
  loki-data:  

networks:
  plg-networks:
